// <auto-generated />
using System;
using IzweAutoService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IzweAutoService.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("IzweAutoService.Domain.Entities.AppSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("app_settings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "General",
                            Key = "BaseFolderPath",
                            Value = "/data/sms"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Sms",
                            Key = "SenderId",
                            Value = "IzweLoans"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Sms",
                            Key = "ClientId",
                            Value = "WireGhana"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Sms",
                            Key = "ApiUrl",
                            Value = "https://api.wirepick.com/httpsms/send"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Sms",
                            Key = "ApiPassword",
                            Value = ""
                        },
                        new
                        {
                            Id = 6,
                            Category = "General",
                            Key = "CronIntervalMinutes",
                            Value = "5"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Smtp",
                            Key = "SmtpHost",
                            Value = ""
                        },
                        new
                        {
                            Id = 8,
                            Category = "Smtp",
                            Key = "SmtpPort",
                            Value = "587"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Smtp",
                            Key = "SmtpUsername",
                            Value = ""
                        },
                        new
                        {
                            Id = 10,
                            Category = "Smtp",
                            Key = "SmtpPassword",
                            Value = ""
                        },
                        new
                        {
                            Id = 11,
                            Category = "Smtp",
                            Key = "SmtpUseSsl",
                            Value = "true"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Alerts",
                            Key = "AlertEmailFrom",
                            Value = ""
                        },
                        new
                        {
                            Id = 13,
                            Category = "Alerts",
                            Key = "AlertEmailTo",
                            Value = ""
                        },
                        new
                        {
                            Id = 14,
                            Category = "Alerts",
                            Key = "AlertsEnabled",
                            Value = "false"
                        },
                        new
                        {
                            Id = 15,
                            Category = "General",
                            Key = "SmsBatchSize",
                            Value = "500"
                        });
                });

            modelBuilder.Entity("IzweAutoService.Domain.Entities.ProcessingLock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AcquiredAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeldBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("LockName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LockName")
                        .IsUnique();

                    b.ToTable("processing_locks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LockName = "SmsProcessing"
                        });
                });

            modelBuilder.Entity("IzweAutoService.Domain.Entities.ProcessingLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalFailed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalFound")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalSent")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.ToTable("processing_logs", (string)null);
                });

            modelBuilder.Entity("IzweAutoService.Domain.Entities.SmsRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ApiCost")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiMessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceFile")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("Country");

                    b.HasIndex("PhoneNumber");

                    b.HasIndex("ProcessedAt");

                    b.HasIndex("Status", "CreatedAt");

                    b.HasIndex("ContractId", "PhoneNumber", "SourceFile")
                        .IsUnique();

                    b.ToTable("sms_records", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
